Extension: StockholmGenomicNucleicAcidSequencingExtensionNumberOfReads
Id: stockholm-genomic-nas-number-of-reads
Title: "Stockholm Genomic Nucleic Acid Sequencing Extension Number of Reads"
Description: "Extension that captures the number of reads generated by nucleic acid sequencing."
Context: Procedure
* ^status = #draft
* value[x] only decimal or integer